### PR TITLE
Update Hugo blog awesome

### PR DESCRIPTION
**Pull request by hugo-sid**
This theme (Hugo blog awesome) was disabled since the demo url was not found.

I have fixed it with this PR.

### Repo

https://github.com/hugo-sid/hugo-blog-awesome

### Demo site
https://hba.sid.one/

### CODE REVIEW

**Comment by hugo-sid** [comment]
Can you please review this @TomasBankauskas ?

Thanks.

**Comment by hugo-sid** [comment]
Is there anything else that I should do/update?

**Comment by hugo-sid** [comment]
Thanks @TomasBankauskas, for merging this PR. 

Currently the thumbnail image shows a 404 page. Can the thumbnail be regenerated?

Let me know If I can to do something to fix this.

**Comment by hugo-sid** [comment]
Thanks for updating the thumbnail @TomasBankauskas.

The screenshot at https://jamstackthemes.dev/theme/hugo-blog-awesome/ shows a 404 page.  Can the screenshot be regenerated?

Let me know If I can to do something to fix this.

**Comment by TomasBankauskas** [comment]
@hugo-sid Thank you for letting me know. It's fixed now -> https://jamstackthemes.dev/theme/hugo-blog-awesome/

**Comment by hugo-sid** [comment]
Thanks for the updating the screenshot @TomasBankauskas.

**Pull request merged**
