### PR TITLE
Create gatsby-clay

### PR DESCRIPTION
**Pull request by lilxyzz**

### CODE REVIEW

**Comment by lilxyzz** [comment]
Hi @TomasBankauskas - I realized that my theme may not be displaying because I forgot to add .md to the file name. What is the quickest way for me to fix this issue? Cheers

**Comment by TomasBankauskas** [comment]
Hi @lilxyzz, thank you for the theme submission. I added a `.md` ending to your file, and you can see your theme [here](https://jamstackthemes.dev/theme/gatsby-clay/). One issue remains, your demo is not accessible in the iframe `Refused to display 'https://clay-theme.netlify.app/' in a frame because it set 'X-Frame-Options' to 'deny'`.

**Comment by lilxyzz** [comment]
Thank you @TomasBankauskas, really appreciate it. It looks like Netlify is adding 'X-Frame-Options'  by default now. I will look into disabling it when I get a moment. Cheers.

**Comment by TomasBankauskas** [comment]
Np @lilxyzz. Regarding `X-Frame-Options`, maybe this documentation will be useful for you -> https://docs.netlify.com/routing/headers/#syntax-for-the-headers-file

**Pull request merged**
